name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: tests
    strategy:
      matrix:
        include:
          - { name: Linux, python: '3.10', os: ubuntu-latest }
          - { name: Windows, python: '3.10', os: windows-latest }
          - { name: Mac, python: '3.10', os: macos-latest }
          - { name: '3.11', python: '3.11', os: ubuntu-latest }
          - { name: '3.9', python: '3.9', os: ubuntu-latest }
          - { name: '3.8', python: '3.8', os: ubuntu-latest }
          - { name: '3.7', python: '3.7', os: ubuntu-latest }
          - { name: '3.6', python: '3.6', os: ubuntu-latest }
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox tox-gh-actions
      - run: tox
